(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], wait=n=>new Promise(r=>setTimeout(r,n));
  const ids=['cinder','orchard','seafoam','moth','sill','vial'];
  const R={cinder:{name:'CINDER',type:'cinder'},orchard:{name:'ORCHARD',type:'orchard'},seafoam:{name:'SEAFOAM',type:'seafoam'},moth:{name:'MOTH',type:'moth'},sill:{name:'SILL',type:'sill'},vial:{name:'VIAL',type:'vial'}};
  const P={'cinder>orchard':'THE BURNING GRAFT','cinder>seafoam':'THE GLASS SPARK','cinder>moth':'THE LIT WING','cinder>sill':'THE HINGE OF FIRE','cinder>vial':'THE RED TINCTURE','orchard>cinder':'THE ROOTED FLAME','orchard>seafoam':'THE SALT GARDEN','orchard>moth':'THE POLLEN VEIL','orchard>sill':'THE GREEN DOOR','orchard>vial':'THE GRAFTED VIAL','seafoam>cinder':'THE TIDE’S EMBER','seafoam>orchard':'THE REFLECTING GROVE','seafoam>moth':'THE WET WING','seafoam>sill':'THE LOW HORIZON','seafoam>vial':'THE BRINE VESSEL','moth>cinder':'THE ASHEN CHRYSALIS','moth>orchard':'THE NIGHT BLOOM','moth>seafoam':'THE LUNAR FOAM','moth>sill':'THE OPEN WING','moth>vial':'THE CAPTURED DUST','sill>cinder':'THE WARM THRESHOLD','sill>orchard':'THE GARDEN GATE','sill>seafoam':'THE TIDELINE','sill>moth':'THE CHANGING DOOR','sill>vial':'THE SEALED PASSAGE','vial>cinder':'THE KEPT SPARK','vial>orchard':'THE ROOT TONIC','vial>seafoam':'THE BLUE ELIXIR','vial>moth':'THE WINGED DISTILLATE','vial>sill':'THE STORED KEY'};
  const saved=(()=>{try{return JSON.parse(localStorage.getItem('citadel-compounds')||'[]')}catch{return[]}})();
  const s={deck:[],hand:[],discard:[],picked:[],discoveries:new Set(saved),cycle:1,last:null,working:false};
  const q=a=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  function art(id){return `<figure class="relic-art ${id}"><canvas class="relic-canvas" data-kind="${id}" aria-label="${R[id].name} material study"></canvas></figure>`}
  function card(id,dealt=false){const x=R[id],p=s.picked.indexOf(id);return `<button class="tarot-card type-${x.type}${p>-1?' selected':''}${dealt?' dealt':''}" data-id="${id}" role="listitem" aria-label="${x.name}" aria-pressed="${p>-1}"><span class="card-frame"><span class="card-core">${art(id)}<span class="card-name">${x.name}</span></span></span>${p>-1?`<i class="order">${p+1}</i>`:''}</button>`}
  function stageCard(id){return `<span class="stage-card type-${R[id].type}">${art(id)}</span>`}
  function draw(){const dealt=[];let reshuffle=false;while(s.hand.length<4){if(!s.deck.length){if(!s.discard.length)break;s.deck=q([...s.discard]);s.discard=[];s.cycle++;reshuffle=true}s.hand.push(s.deck.pop());dealt.push(s.hand[s.hand.length-1])}return{dealt,reshuffle}}
  function renderStage(){const c=$('#stageCards'),n=$('#compoundName');c.className=`stage-cards${s.picked.length===2?' pair':''}`;c.innerHTML=s.picked.map(stageCard).join('');n.textContent=s.picked.length===2?P[`${s.picked[0]}>${s.picked[1]}`]:s.picked.length===1?'SECOND RELIC':s.last||'TAKE TWO'}
  function renderPile(){const top=s.discard.at(-1);$('#deckPile').className='pile deck';$('#deckPile').innerHTML='<span></span>';$('#discardPile').className=`pile discard${top?'':' empty'}${top?` type-${R[top].type}`:''}`;$('#discardPile').innerHTML=`<span>${top?art(top):''}</span>`;$('#deckCount').textContent=s.deck.length;$('#discardCount').textContent=s.discard.length;$('#cycleCount').textContent=['I','II','III','IV','V','VI'][s.cycle-1]||s.cycle;$('#discoveryCount').textContent=s.discoveries.size}
  function render(o={}){$('#hand').innerHTML=s.hand.map(x=>card(x,o.dealt?.includes(x))).join('');$$('#hand .tarot-card').forEach(x=>{x.addEventListener('click',()=>pick(x.dataset.id));x.addEventListener('pointermove',tilt);x.addEventListener('pointerleave',e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')})});renderStage();renderPile();$('#clearButton').disabled=!s.picked.length||s.working;$('#combineButton').disabled=s.picked.length!==2||s.working;if(o.reshuffle)$('#deckPile').classList.add('reshuffle');paint()}
  function tilt(e){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',`${((e.clientY-r.top)/r.height-.5)*-6}deg`);e.currentTarget.style.setProperty('--tilt-y',`${((e.clientX-r.left)/r.width-.5)*6}deg`)}
  function pick(id){if(s.working)return;const i=s.picked.indexOf(id);if(i===0)s.picked=[];else if(i===1)s.picked=[s.picked[0]];else if(s.picked.length<2)s.picked.push(id);else s.picked=[id];render()}
  async function fly(ids){const end=$('#stage').getBoundingClientRect(),clones=ids.map((id,i)=>{const source=$(`.tarot-card[data-id="${id}"]`),r=source.getBoundingClientRect(),c=source.cloneNode(true);c.classList.remove('selected','dealt');c.classList.add('flight');c.style.cssText+=`left:${r.left}px;top:${r.top}px;width:${r.width}px;height:${r.height}px;--x:${end.left+end.width*(i?.57:.43)-r.left-r.width/2}px;--y:${end.top+end.height*.42-r.top-r.height/2}px;--r:${i?5:-5}deg`;document.body.append(c);requestAnimationFrame(()=>c.classList.add('fly'));return c});await wait(520);clones.forEach(x=>x.remove())}
  async function combine(){if(s.working||s.picked.length!==2)return;s.working=true;const pair=[...s.picked];await fly(pair);s.last=P[`${pair[0]}>${pair[1]}`];s.discoveries.add(`${pair[0]}>${pair[1]}`);try{localStorage.setItem('citadel-compounds',JSON.stringify([...s.discoveries]))}catch{}s.hand=s.hand.filter(x=>!pair.includes(x));s.discard.push(...pair);s.picked=[];const dealt=draw();s.working=false;render(dealt)}
  function reset(){s.deck=q([...ids]);s.hand=[];s.discard=[];s.picked=[];s.cycle=1;s.last=null;s.working=false;render(draw())}
  const ink={cinder:['#210b14','#8a112d','#ef3e5b','#ffc79a'],orchard:['#071817','#075447','#56ae78','#daefae'],seafoam:['#08212b','#19576a','#6fb7be','#e4f0d8'],moth:['#25132d','#6b286c','#b467ad','#f2b6dc'],sill:['#111934','#344d8a','#8ca7dc','#edf0c8'],vial:['#08201d','#275d53','#78b89a','#e7d39b']};
  function random(seed){let n=seed;return()=>((n=n*1664525+1013904223>>>0)/4294967296)}function paint(){requestAnimationFrame(()=>$$('.relic-canvas').forEach(c=>{const kind=c.dataset.kind,w=c.clientWidth,h=c.clientHeight,d=Math.max(2,devicePixelRatio||1);c.width=w*d;c.height=h*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);const a=ink[kind],r=random([...kind].reduce((n,z)=>n+z.charCodeAt(0),0));x.fillStyle=a[0];x.fillRect(0,0,w,h);for(let i=0;i<42;i++){const gx=r()*w,gy=r()*h,rad=(.05+r()*.22)*Math.max(w,h),g=x.createRadialGradient(gx,gy,0,gx,gy,rad);g.addColorStop(0,a[2]+(r()>.5?'4c':'29'));g.addColorStop(1,'transparent');x.fillStyle=g;x.fillRect(0,0,w,h)}x.globalAlpha=.18;x.strokeStyle=a[3];x.lineWidth=1;for(let i=0;i<25;i++){x.beginPath();x.moveTo(-w*.2,r()*h);x.lineTo(w*1.2,r()*h);x.stroke()}x.globalAlpha=1;x.strokeStyle=a[3];x.fillStyle=a[2];x.lineWidth=Math.max(1,w*.012);const cx=w/2,cy=h*.55;if(kind==='cinder'){x.beginPath();x.moveTo(cx,cy-h*.3);x.bezierCurveTo(cx+w*.28,cy-h*.04,cx-w*.18,cy+h*.1,cx,cy+h*.3);x.bezierCurveTo(cx-w*.25,cy+h*.05,cx+w*.08,cy-h*.12,cx,cy-h*.3);x.fill();x.fillStyle=a[3];x.beginPath();x.ellipse(cx,cy,w*.08,h*.17,0,0,7);x.fill()}else if(kind==='orchard'){x.beginPath();x.moveTo(cx,cy-h*.36);x.lineTo(cx,cy+h*.32);x.stroke();for(let i=0;i<7;i++){const y=cy-h*.22+i*h*.075,side=i%2?1:-1;x.beginPath();x.ellipse(cx+side*w*.15,y,w*.13,h*.055,side*.7,0,7);x.fill()}}else if(kind==='seafoam'){x.fillStyle=a[3];x.beginPath();x.arc(cx,cy-h*.22,w*.17,0,7);x.fill();x.fillStyle=a[2];for(let i=0;i<4;i++){x.beginPath();x.moveTo(-w*.1,cy+i*h*.09);for(let j=0;j<4;j++)x.quadraticCurveTo(w*(j*.32+.15),cy+i*h*.09-h*.07,w*(j*.32+.32),cy+i*h*.09);x.lineTo(w*1.1,h);x.lineTo(-w*.1,h);x.fill()}}else if(kind==='moth'){x.fillStyle=a[2];for(const side of[-1,1]){x.beginPath();x.ellipse(cx+side*w*.16,cy,w*.18,h*.22,side*.5,0,7);x.fill()}x.fillStyle=a[3];x.fillRect(cx-w*.025,cy-h*.28,w*.05,h*.56)}else if(kind==='sill'){x.strokeStyle=a[3];x.lineWidth=w*.025;x.beginPath();x.arc(cx,cy+h*.05,w*.24,Math.PI,0);x.lineTo(cx+w*.24,cy+h*.31);x.lineTo(cx-w*.24,cy+h*.31);x.closePath();x.stroke();x.fillStyle=a[3];x.beginPath();x.ellipse(cx,cy,w*.07,h*.2,0,0,7);x.fill()}else{x.strokeStyle=a[3];x.lineWidth=w*.025;x.beginPath();x.roundRect(cx-w*.2,cy-h*.32,w*.4,h*.62,w*.08);x.stroke();x.fillStyle=a[2];x.beginPath();x.ellipse(cx,cy+h*.11,w*.14,h*.15,0,0,7);x.fill()}const v=x.createLinearGradient(0,0,0,h);v.addColorStop(0,'transparent');v.addColorStop(1,'rgba(0,0,0,.58)');x.fillStyle=v;x.fillRect(0,0,w,h)}))}
  function sky(){const c=$('#sky'),x=c.getContext('2d');let o=[];const resize=()=>{const d=devicePixelRatio||1;c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0);o=Array.from({length:6},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,s:Math.max(innerWidth,innerHeight)*(.24+Math.random()*.25),p:Math.random()*7,c:i%2?'#4a9b87':'#3e728f'}))};resize();addEventListener('resize',resize);const draw=t=>{x.fillStyle='#061315';x.fillRect(0,0,innerWidth,innerHeight);o.forEach(v=>{const q=x.createRadialGradient(v.x+Math.sin(t*.00005+v.p)*60,v.y,0,v.x,v.y,v.s);q.addColorStop(0,v.c+'1c');q.addColorStop(1,'transparent');x.fillStyle=q;x.fillRect(0,0,innerWidth,innerHeight)});requestAnimationFrame(draw)};draw(0)}
  $('#clearButton').addEventListener('click',()=>{s.picked=[];render()});$('#combineButton').addEventListener('click',combine);$('#resetButton').addEventListener('click',reset);document.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();combine();return}if(e.key==='Escape'){s.picked=[];render();return}const n=Number(e.key)-1;if(n>=0&&n<s.hand.length)pick(s.hand[n])});sky();reset();
})();
